# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s.split(" ")

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print("The diameter of Earth is {} kilometers.".format(diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
result=d['k1'][3]['tricky'][3]['target'][3]
print(result)

hello


# Numpy

In [2]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [3]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
arr1=np.ones(10)*5
print(arr1)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [5]:
arr2=np.arange(20,35,2)
print(arr2)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [7]:
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.concatenate((n1,n2),axis=0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [8]:
import pandas as pd
import numpy as np


In [ ]:
array=np.random.randint(10,size=(3,2))
array=([9,2,2],
      [3,5,1],
        [4,9,8],
      [3,4,5])
df=pd.DataFrame(array)
df

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [1]:
dRan3 = pd.date_range(start ='2023-01-01', end ='2023-02-10').to_pydatetime().tolist()
print(dRan3)

NameError: name 'pd' is not defined

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
df = pd.DataFrame(lists, columns =['ID', 'number','no']) 
print(df)